# Generated by Django 5.1.3 on 2024-12-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_favouritefilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritefilm',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
