# Generated by Django 5.1.3 on 2024-12-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_favouritefilm_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouritefilm',
            name='is_favourite',
        ),
    ]
