# Generated by Django 5.1.3 on 2024-12-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_favouritefilm_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritefilm',
            name='heart_image',
            field=models.CharField(default='heart-n.svg', max_length=255),
        ),
    ]
