# Generated by Django 5.1.3 on 2024-12-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_favouritefilm_heart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
